# Change these first
owner: gaeljw # Your GitHub username
repo: poc-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: theGardener
    url: https://thegardener.kelkoogroup.com/
  - name: developers.kkg
    url: https://developers.kelkoogroup.com/
  - name: Test SAPISEARCH
    url: $SAPISEARCH_URL
    headers:
    - "Authorization: Bearer $SAPISEARCH_TOKEN"
    - "Content-Type: application/json"
    - "Accept-Encoding: gzip"
  - name: Test SAPILM
    url: $SAPILM_URL
    headers:
    - "Authorization: Bearer $SAPISEARCH_TOKEN"
    - "Content-Type: application/json"
    - "Accept-Encoding: gzip"
    expectedStatusCodes:
    - 200
    - 404
    __dangerous__body_down: "No context-path matches the request URI"
  - name: Test SFEEDMERCHANT
    url: $SFEEDMERCHANT_URL
    headers:
    - "Authorization: Bearer $SAPISEARCH_TOKEN"
    - "Content-Type: application/json"
    - "Accept-Encoding: gzip"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /poc-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Customizable intro title"
  introMessage: Customizable intro message
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "1/5 * * * *"
  responseTime: "*/5 * * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
